version: "3"

services:
  app:
    build: docker/php
    volumes:
      - ./app:/app

  nginx:
    image: nginx:1.12-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/vhost.conf
    depends_on:
      - app